defaults:
  - bert.yaml

_target_: lewidi.data.tokenizers.AraBERTTokenizer

tokenizer:
  pretrained_model_name_or_path: aubmindlab/bert-base-arabertv02

preprocessor: 
  _target_: arabert.preprocess.ArabertPreprocessor
  model_name: aubmindlab/bert-base-arabertv02

tokenize_kwargs:
  padding: max_length
  return_attention_mask: true
