_target_: lewidi.models.LeWiDiSingleTaskModel

backbone:
  _target_: transformers.AutoModel.from_pretrained
  pretrained_model_name_or_path: bert-base-uncased

head:
  _target_: lewidi.models.components.ClassifierHead
  input_dim: 768
  num_labels: 2

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
